ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "gmailAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "mailCursor" TEXT,
  ADD COLUMN IF NOT EXISTS "mailLease" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "mailLeaseId" TEXT,
  ADD COLUMN IF NOT EXISTS "mailStatus" TEXT NOT NULL DEFAULT 'IDLE',
  ADD COLUMN IF NOT EXISTS "mailError" TEXT,
  ADD COLUMN IF NOT EXISTS "mailImported" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "mailLastSync" TIMESTAMP(3);

CREATE TABLE IF NOT EXISTS "GmailOAuthState" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "browserHash" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "GmailOAuthState_pkey" PRIMARY KEY ("id")
);
